name: CD

on:
  push:
    tags: '*'

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Makefile
        run: |
          echo "CFLAGS=-Wall -Werror" > config.mk
          echo "LDFLAGS=-lm -fsanitize=address" >> config.mk
      - name: Build
        run: make
      - name: Run
        run: chmod +x mdp && ./mdp
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdp-linux
          path: mdp
          if-no-files-found: error
  build-win:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64
      - name: Configure Makefile
        run: |
          echo "CC=x86_64-w64-mingw32-gcc" > config.mk
          echo "CFLAGS=-Wall -Werror -D__USE_MINGW_ANSI_STDIO" >> config.mk
          echo "LDFLAGS=-lm" >> config.mk
      - name: Build
        run: make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdp-windows
          path: mdp.exe
          if-no-files-found: error
  release:
    name: Release
    if: github.repository == 'p2sr/mdp'
    needs: [build-lin, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Version
        id: get_release
        run: echo ::set-output name=version::${GITHUB_REF:10}
      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: mdp-linux
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: mdp-windows
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ![CD](https://github.com/p2sr/mdp/workflows/CD/badge.svg)

            **Installation**
            - Download:
              - [Windows](https://github.com/p2sr/mdp/releases/download/${{ steps.get_release.outputs.version }}/mdp.exe)
              - [Linux](https://github.com/p2sr/mdp/releases/download/${{ steps.get_release.outputs.version }}/mdp)
                - Run `chmod +x mdp`

            ---

            **Changelog**
            TODO
          files: |
            mdp
            mdp.exe
          prerelease: false
          fail_on_unmatched_files: true
