name: CI

# FIXME: LDFLAGS -fsanitize=address on mingw
# https://stackoverflow.com/a/55019187

# TODO: Test run on windows

on:
  push:
    paths:
      - "src/**/*.c"
      - "src/**/*.h"
  pull_request:
    paths:
      - "src/**/*.c"
      - "src/**/*.h"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-lin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Makefile
        run: |
          echo "CFLAGS=-Wall -Werror" > config.mk
          echo "LDFLAGS=-lm -fsanitize=address" >> config.mk
      - name: Build
        run: make
      - name: Run
        run: chmod +x mdp && ./mdp
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdp-linux
          path: mdp
          if-no-files-found: error
  build-win:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64
      - name: Configure Makefile
        run: |
          echo "CC=x86_64-w64-mingw32-gcc" > config.mk
          echo "CFLAGS=-Wall -Werror -D__USE_MINGW_ANSI_STDIO" >> config.mk
          echo "LDFLAGS=-lm" >> config.mk
      - name: Build
        run: make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdp-windows
          path: mdp.exe
          if-no-files-found: error
